name: Deploy to EC2 via Docker (API + ADMIN)

on:
    push:
        branches: [ "main" ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Configure AWS CLI
              run: |
                  aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws configure set region ap-northeast-2

            - name: Build without Tests
              run: ./gradlew clean build -x test

            - name: Login to ECR
              run: |
                  aws ecr get-login-password --region ap-northeast-2 | \
                  docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

            - name: Build and Push Docker Images
              run: |
                  docker build -t ${{ secrets.ECR_REPOSITORY }}:api-server ./api-server
                  docker push ${{ secrets.ECR_REPOSITORY }}:api-server

                  docker build -t ${{ secrets.ECR_REPOSITORY }}:admin-server ./admin-server
                  docker push ${{ secrets.ECR_REPOSITORY }}:admin-server

            - name: Deploy on EC2
              run: |
                  echo "${{ secrets.EC2_KEY }}" | base64 --decode > key.pem
                  chmod 400 key.pem

                  ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                    aws ecr get-login-password --region ap-northeast-2 | \
                    docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

                    docker pull ${{ secrets.ECR_REPOSITORY }}:api-server
                    docker pull ${{ secrets.ECR_REPOSITORY }}:admin-server

                    docker rm -f api-server || true
                    docker rm -f admin-server || true

                    docker run -d --name api-server \
                      -e SPRING_PROFILES_ACTIVE=api \
                      -e SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
                      -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
                      -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
                      -p 8080:8080 ${{ secrets.ECR_REPOSITORY }}:api-server

                    docker run -d --name admin-server \
                      -e SPRING_PROFILES_ACTIVE=admin \
                      -e SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
                      -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
                      -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
                      -p 8081:8081 ${{ secrets.ECR_REPOSITORY }}:admin-server
                  EOF
