name: Deploy to EC2 via Docker

on:
    push:
        branches: [ "main" ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Set up Docker
              uses: docker/setup-buildx-action@v3

            - name: Configure AWS CLI
              run: |
                  aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws configure set region ap-northeast-2

            - name: Build and Test with Gradle
              run: ./gradlew clean build

            - name: Login to ECR
              run: |
                  aws ecr get-login-password --region ap-northeast-2 | \
                  docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

            - name: Build and Push Docker Image
              run: |
                  docker build -t ${{ secrets.ECR_REPOSITORY }} .
                  docker push ${{ secrets.ECR_REPOSITORY }}

            - name: Deploy on EC2
              run: |
                  echo "${{ secrets.EC2_KEY }}" | base64 --decode > key.pem
                  chmod 400 key.pem

                  ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
                    echo "SPRING_DATASOURCE_URL=${{ secrets.DB_URL }}" > .env
                    echo "SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
                    echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

                    docker pull ${{ secrets.ECR_REPOSITORY }}

                    docker stop spring-app || true
                    docker rm spring-app || true

                    docker run -d --name spring-app \
                      --env-file .env \
                      -p 8080:8080 ${{ secrets.ECR_REPOSITORY }}
                  EOF
